### ISSUE TITLE
Code of conduct

### ISSUE THREAD

**Issue by abranczyk** [DRiP-project/meta#16]
We need a code of conduct. 

Perhaps we can use an existing one, say from Pennylane, or from Qiskit for inspiration?

**Comment by Christophe-pere** [comment]
I agree, I find the [LAT code of conduct very interesting](https://www-glast.stanford.edu/codeofconduct.pdf)

**Comment by abranczyk** [comment]
Yes, this is great! There are definitely a lot of sections in the LAT doc that can be directly applied here. 

Here is some info from GitHub about adding a code of conduct: https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-code-of-conduct-to-your-project

From that ref, a couple of good suggestions:
- Research different codes of conduct designed for open source projects. Choose one that reflects your community's standards.
- If you use a code of conduct written by another person or organization, be sure to follow any attribution guidelines from the source. 

The Qiskit code is also worth looking at: https://github.com/Qiskit/qiskit-metapackage/blob/master/CODE_OF_CONDUCT.md

Also, I think there might be a way to make sure that someone explicitly agrees to the code of conduct before being able to make a PR in a repo, but I don't know exactly how this works. We should investigate this.

**Comment by Christophe-pere** [comment]
Thanks for these resources, I will compile everything. I also found papers on Code of Conduct which I will add to make the first draft. 
- [Tourani et al., 2017, Code of conduct in open source projects](http://ieeexplore.ieee.org/document/7884606/)
- [Li et al., 2021, Code of Conduct Conversations in Open Source Software Projects on Github](https://dl.acm.org/doi/10.1145/3449093)

**Comment by Christophe-pere** [comment]
First draft available: 

[🌱 ٤ Code of Conduct DRiP.md](https://github.com/DRiP-project/meta/files/12447056/Code.of.Conduct.DRiP.md)

**Comment by abranczyk** [comment]
Thanks for putting this together @Christophe-pere 

I think it will be easier to iterate on the document if it is stored in the repo, and we edit it on a separate branch that can be merged to main with a pull request when we are happy with it. 

Here is the branch: https://github.com/DRiP-project/meta/tree/code-of-conduct
Here is the document: https://github.com/DRiP-project/meta/blob/code-of-conduct/Code.of.Conduct.DRiP.md
Here is the pull request: https://github.com/DRiP-project/meta/pull/25

**Comment by abranczyk** [comment]
Looks good @Christophe-pere. Would you like to merge the pull request? That will merge it into the meta repo. 

I suggest using the "squash and merge" option to keep the commit history clean. 

<img width="358" alt="Screenshot 2023-09-06 at 7 56 48 AM" src="https://github.com/DRiP-project/meta/assets/41384600/45a3f734-1bfc-4072-965b-e9a7986c5d64">
